name: SCA

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.9 # GitHub Action version
        with:
          project: "test_cxflow_ga" # <-- Insert Checkmarx CxSCA Project Name
          sca_api_url: https://eu.api-sca.checkmarx.net
          sca_app_url: https://eu.sca.checkmarx.net
          sca_access_control_url: https://eu.platform.checkmarx.net
          sca_tenant: "APAC-Support" # <-- Insert Checkmarx CxSCA Tenant
          sca_username: ${{ secrets.CHECKMARX_SCA_USERNAME }} # To be stored in GitHub Secrets.
          sca_password: ${{ secrets.CHECKMARX_SCA_PASSWORD }} # To be stored in GitHub Secrets.
          break_build: false
          scanners: sca
          bug_tracker: Sarif
          params: --checkmarx.settings-override=true --namespace=${{ github.repository_owner }}  --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref_name }} --sca.enable-sca-resolver=true --sca.sca-resolver-add-parameters.log-level=Debug --logging.level.com.checkmarx.flow.service=DEBUG --logging.level.org.springframework.web.client.RestTemplate=TRACE
