name: SCA

on:
  pull_request:
    branches: [ master, main ]

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.9 # GitHub Action version
        with:
          project: "Github_pull_bug" # <-- Insert Checkmarx CxSCA Project Name
          sca_api_url: https://eu.api-sca.checkmarx.net
          sca_app_url: https://eu.sca.checkmarx.net
          sca_access_control_url: https://eu.platform.checkmarx.net
          sca_tenant: "APAC-Support" # <-- Insert Checkmarx CxSCA Tenant
          sca_username: ${{ secrets.CHECKMARX_SCA_USERNAME }} # To be stored in GitHub Secrets.
          sca_password: ${{ secrets.CHECKMARX_SCA_PASSWORD }} # To be stored in GitHub Secrets.
          break_build: false
          scanners: sca
          bug_tracker: GITHUBPULL
          params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=master --merge-id=10000 --sca.sca-resolver-add-parameters.log-level=Debug --logging.level.com.checkmarx.flow.service=DEBUG --logging.level.org.springframework.web.client.RestTemplate=TRACE
